### ISSUE TITLE
Findings from Playtest session

### ISSUE THREAD

**Issue by Laguna1989** [runvs/Kajam-13#41]
- [x]  unlock mechanik nicht klar
- [x]  geld jetzt für weniger Geld in nächster Runde
- [x]  upgrades nicht intuitiv klar
- [x]  initiale cannon range zu groß. dafür schnelleres nachladen und mehr schaden?
- [x]  max geld pro runde limitieren
- [x]  timer mit max time runter zählen lassen 	
- [x]  peasant mit rage ist zu schnell
- [x]  ~~Preise der einheiten staffeln. Lv1 (50), Lv2 (100), Lv3(200)~~
- [x]  Einheitenlevel auf 10 begrenzen
- [x]  tooltips für Upgrades
- [x]  alle einheiten unlocked crashed game
- [x]  starting unit window size
- [x]  unlock erst ab späteren Runden
- [x]  nur eine Einheit pro runde unlocken
- [x] ~~#44 gegen Kosten länger stehende Einheiten verschieben~~
- [x] ~~#44 in der selben Runde frisch gestellte Einheiten kostenlos verschieben~~
- [x] ~~#45~~
- [x]  unit placement kleiner machen (dreieck) crashed
- [x]  range von units bevor die Einheit steht
- [x]  ~~starting unit combi rausvoten?~~
- [x]  startgeld für peasant cannon combi, damit man sich eine cannon kaufen kann
- [x]  wenn drei runden verloren, looser buffen
- [x]  horseman xp needed for level up etwas höher 
- [x]  buffer erhöhen
- [x]  swordman gegen horseman
- [x]  einheiten schauen manchmal in falsche richtung

**Comment by Semitalis** [comment]
Done with #46
